#!/usr/bin/env ruby

require "./src/alegria"

# Signal.trap('SIGUSR1') { Alegria.back }
# Signal.trap('SIGUSR2') { Alegria.forward }
# Signal.trap('SIGWINCH') { Alegria.start_slideshow }

minimize_windows
hide_mouse_cursor

auto_reboot
auto_git_pull
auto_hide_cursor

day = Time.new.strftime("%a")

while true
  if Alegria.open?
    if day == "Sat" # ||  day == "Fri"
      Alegria.pcmanfm_wallpaper(jpg_for_today "images/01/slideshow")
    else
      Alegria.pcmanfm_wallpaper(jpg_for_today "images/01/bible_slideshow")
    end
  else
    Alegria.pcmanfm_wallpaper(jpg_for_min "images/01/closed")
  end # if Alegria.open?

  sleep_to_min
end # while




