#!/usr/bin/env ruby

require "./src/alegria"

# Signal.trap('SIGUSR1') { Alegria.back }
# Signal.trap('SIGUSR2') { Alegria.forward }
# Signal.trap('SIGWINCH') { Alegria.start_slideshow }

minimize_windows
hide_mouse_cursor

auto_reboot
auto_git_pull
auto_hide_cursor

day = Time.new.strftime("%a")

while true
  Alegria.pcmanfm_wallpaper("images/01/cheese_bread.png")
  sleep_to_min
  while !on_15th_minute?
    sleep_to_min
  end
end # while




