#!/usr/bin/env zsh
#
#
set -u -e -o pipefail


if ! test "$USER" = "pi" ; then
  set -x
fi

cd $HOME/apps/alegria
mkdir -p tmp

killall lemonbar || :
killall mpv || :
killall smplayer || :
killall vlc || :


# Get the mouse out of the way:
( sh/01/hide_cursor || : ) &

# Auto-update:
( sh/auto_update.sh || : ) &
( sh/auto_reboot.sh || : ) &

# Minimize any windows.
for x in $(wmctrl -l | cut -d' ' -f1); do
  xdotool windowminimize "$x" || :
done


# TOP CAPTION:
# ( sh/01/time || : ) &

( sh/01/wallpaper || : ) &

# Order Here sign:
# ( sh/01/order_here || : ) &

while sh/is.running ; do
  sh/sleep.minute
done

echo "=== Done main: $$"

