#!/usr/bin/env sh
#
#
set -u -e

PATH="$PATH:$HOME/progs/lemonbar-xft"

cd $HOME/apps/alegria

pkill -f time_caption || :
sh/01/time.text | sh/01/time.bar

exit 0
bar_pid=""
sh/01/top.text | sh/01/top.bar

# while sh/is.running ; do
#   if ! pgrep -f top_bar_caption &> /dev/null ; then
#     echo "=== Starting a new $0 (top bar)..."
    # ( sh/01/top.text | sh/01/top.bar ) &
    # bar_pid="$!"
    # echo "TOP BAR CAPTION PID: $bar_pid"
  # fi
  # sh/sleep.minute
# done

echo "=== DONE: $0"




