#!/usr/bin/env zsh
#
#
set -u -e -o pipefail


cd $HOME/apps/alegria

while sh/is.running ; do
  if sh/is.stroganoff.special ; then
    pcmanfm --set-wallpaper $PWD/wall_display/01/stroganoff.01.jpg --wallpaper-mode=fit
    sh/sleep.hour
    continue
  fi

  if sh/is.kids.special ; then
    pcmanfm --set-wallpaper $PWD/wall_display/01/kids.special.01.jpg --wallpaper-mode=fit
    sh/sleep.hour
    continue
  fi

  if sh/is.closed ; then
    pcmanfm --set-wallpaper $PWD/images/final/01/brazil_coffee_candy.jpg --wallpaper-mode=fit
    sh/sleep.hour
    continue
  fi

  if sh/is.closing.soon ; then
    pcmanfm --set-wallpaper $PWD/images/final/01/mark_11_24.jpg --wallpaper-mode=fit
    sh/sleep.minute
    continue
  fi

  for x in $(find wall_display/01 -type f -name 'order_here.*.jpg') ; do
    if sh/is.closing.soon || sh/is.closed ; then
      continue
    fi
    pcmanfm --set-wallpaper "$PWD/$x" --wallpaper-mode=fit
    sh/sleep.minute
  done
done # while
