#!/usr/bin/env zsh
#
#
set -u -e -o pipefail


cd $HOME/apps/alegria

while sh/is.running ; do
  if sh/is.stroganoff.special ; then
    pcmanfm --set-wallpaper $PWD/wall_display/01/stroganoff.01.jpg --wallpaper-mode=fit
    sh/sleep.hour
    continue
  fi

  if sh/is.kids.special ; then
    pcmanfm --set-wallpaper $PWD/wall_display/01/kids.special.01.jpg --wallpaper-mode=fit
    sh/sleep.hour
    continue
  fi

  if sh/is.closed ; then
    pcmanfm --set-wallpaper $PWD/wall_display/01/closed.01.jpg --wallpaper-mode=fit
    sh/sleep.hour
    continue
  fi

  if sh/is.closing.soon ; then
    pcmanfm --set-wallpaper $PWD/wall_display/01/closing.soon.jpg --wallpaper-mode=fit
    sh/sleep.minute
    continue
  fi

  while sh/is.open && ! sh/is.closing.soon ; do
    for x in $(find wall_display/01 -type f -name 'order_here.*.jpg') ; do
      if sh/is.closing.soon ; then
        continue
      fi
      pcmanfm --set-wallpaper "$PWD/$x" --wallpaper-mode=fit
      sh/sleep.minute
    done
  done
done # while
