#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

blue="#132492"
white="#ffffff"

if ! test "$USER" = "pi" ; then
  set -x
fi

cd $HOME/apps/alegria
mkdir -p tmp

killall lemonbar || :
killall mpv || :
killall smplayer || :
killall vlc || :

# Minimize any windows.
for x in $(wmctrl -l | cut -d' ' -f1); do
  xdotool windowminimize "$x" || :
done

# Auto-update:
( sh/auto_update.sh || : ) &

( sh/auto_reboot.sh || : ) &

# Get the mouse out of the way:
( sh/tv/mouse.move || : ) &

# Movies:
# ( sh/tv/movies || : ) &

# BOTTOM CAPTION:
( sh/tv/time || : ) &

setterm -blank 0 -powerdown 0 || :
# Photo Loop:
while sh/is.running ; do

  if sh/is.open ; then
    pcmanfm --set-wallpaper "$PWD/images/final/tv/dec.jpg" --wallpaper-mode=crop || :
    sh/sleep.hour
    # for x in $(find images/final/tv/ -type f -iname "main.jpg" ) ; do
    #   if sh/is.closed ; then
    #     continue
    #   fi
    #   pcmanfm --set-wallpaper "$PWD/$x" --wallpaper-mode=crop || :
    #   sh/sleep.minute
    # done
  else
    pcmanfm --set-wallpaper "$PWD/wall_display/special/mark_11.24.jpg" --wallpaper-mode=crop || :
    sh/sleep.hour
  fi

done # while

