#!/usr/bin/env zsh
#
#
set -u -e -o pipefail

blue="#132492"
white="#ffffff"

if ! test "$USER" = "pi" ; then
  set -x
fi

cd $HOME/apps/alegria
mkdir -p tmp

killall lemonbar || :
killall mpv || :
killall smplayer || :
killall vlc || :

# Minimize any windows.
for x in $(wmctrl -l | cut -d' ' -f1); do
  xdotool windowminimize "$x" || :
done


# Auto-update:
( sh/auto_update.sh || : ) &

# Get the mouse out of the way:
( sh/tv/mouse.move || : ) &

# Movies:
# ( sh/tv/movies || : ) &


# TOP CAPTION:
# ( sh/tv/top.caption || : ) &

# Middle Caption:
( sh/tv/middle.caption || : ) &

# BOTTOM CAPTION:
# ( sh/tv/time || : ) &

# Photo Loop:
while sh/is.running ; do
  seconds="$(date +"%S")"
  minute="$(date +"%M")"

  if sh/is.closed ; then
    if sh/is.opening ; then
      # pcmanfm --set-wallpaper $(sh/random.photo $PWD/wall_display/humor) --wallpaper-mode=crop
    # else
      pcmanfm --set-wallpaper $PWD/wall_display/closing/closed.jpg --wallpaper-mode=crop
    fi
    sh/sleep.minute
    continue
  fi

  if sh/is.closing.soon ; then
    sh/sleep.minute
    continue
  fi

  for x in $(find images/final/tv/ -type f -iname "*.jpg" ) ; do
    if sh/is.closing.soon ; then
      continue
    fi
    pcmanfm --set-wallpaper "$PWD/$x" --wallpaper-mode=crop || :
  done

done # while

