#!/usr/bin/env ruby

include "../alegria"

minimize_windows
hide_mouse_cursor

auto_reboot
auto_git_pull
auto_hide_cursor

while true
  if Alegria.open?
    Alegria.pcmanfm_wallpaper("images/final/tv/dec.jpg")
  else
    Alegria.pcmanfm_wallpaper("images/final/tv/closed/airplane.jpg")
  end # if Alegria.open?

  sleep_to_min
end # while
