#!/usr/bin/env ruby

require "./src/alegria"

minimize_windows
hide_mouse_cursor

auto_reboot
auto_git_pull
auto_hide_cursor

while true
  Alegria.pcmanfm_wallpaper("images/tv/slideshow/01.jpg")
  sleep_to_min
  while !on_15th_minute?
    sleep_to_min
  end
end # while
