#!/usr/bin/env ruby

require "./src/alegria"

minimize_windows
hide_mouse_cursor

auto_reboot
auto_git_pull
auto_hide_cursor

while true
  if Alegria.open?
    Alegria.pcmanfm_wallpaper(jpg_for_min "images/tv/slideshow")
  else
    Alegria.pcmanfm_wallpaper(jpg_for_min "images/tv/closed")
  end # if Alegria.open?

  sleep_to_min
end # while
