#!/usr/bin/env ruby

require "./src/alegria"

minimize_windows
hide_mouse_cursor

auto_reboot
auto_git_pull
auto_hide_cursor
Alegria.pcmanfm_desktop_off

while true
  if Alegria.open?
    Alegria.feh_bg_center("images/menu/menu_01.png", "images/menu/menu_02.png")
  end # if Alegria.open?

  sleep_to_hour
end # while
